---
- name: ansible-media - quick start https://www.raspberrypi.org/forums/viewtopic.php?t=152490&p=999528
  hosts: rpi
  become_user: pi
  become: yes

  tasks:    
    - name: To disable hostapd
      command: update-rc.d -f hostapd remove
      become_user: root
      become: yes
    - name: To disable dnsmasq 
      command: update-rc.d -f dnsmasq remove
      become_user: root
      become: yes
   
    - name: Update repro 1
      lineinfile:
        create: yes
        state: present
        dest: /etc/apt/sources.list
        line: 'deb http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free'
      become_user: root
      become: yes

    - name: Update repro 2
      lineinfile:
        create: yes
        state: present
        dest: /etc/apt/sources.list
        line: '#deb-src http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free'
      become_user: root
      become: yes
      
    - name: Update gpg pgpkeys.mit.edu1
      command: "gpg --keyserver pgpkeys.mit.edu --recv-key CCD91D6111A06851"

    - name: Update gpg pgpkeys.mit.edu2
      command: "gpg --armor --export CCD91D6111A06851 | sudo apt-key add -"

    - name: Update apt-get cache
      apt: >
        update_cache=yes
        cache_valid_time=360   
      become_user: root
      become: yes

    - name: Update all packages to the latest version
      apt: > 
        upgrade=yes
      become_user: root
      become: yes

    - name: Update repositories cache and install "php5-common" package
      apt: 
        name: php5-common 
      become_user: root
      become: yes
    - name: Update repositories cache and install "php5-cgi" package
      apt:
        name: php5-cgi
      become_user: root
      become: yes
    - name: Update repositories cache and install "php5" package
      apt:
        name: php5
      become_user: root
      become: yes
    - name: Update repositories cache and install "lighttpd" package
      apt:
        name: lighttpd
      become_user: root
      become: yes
    - name: Update repositories cache and install "hostapd" package
      apt:
        name: hostapd
      become_user: root
      become: yes
    - name: Update repositories cache and install "dnsmasq" package
      apt:
        name: dnsmasq
      become_user: root
      become: yes
    - name: Update repositories cache and install "ntfs-3g" package
      apt:
        name: ntfs-3g
      become_user: root
      become: yes
    - name: Update repositories cache and install "minidlna" package
      apt:
        name: minidlna
      become_user: root
      become: yes
    - name: Update repositories cache and install "samba" package
      apt:
        name: samba
      become_user: root
      become: yes
    - name: Update repositories cache and install "samba-common-bin" package
      apt:
        name: samba-common-bin
      become_user: root
      become: yes
    - name: Update repositories cache and install "usbmount" package
      apt:
        name: usbmount
      become_user: root
      become: yes

    - name: Setup Lighttpd /var/www
      file:
        path: /var/www
        owner: www-data
        group: www-data
        mode: 0755
      become_user: root
      become: yes

    - name: Setup Lighttpd users
      user:
        name: pi
        groups: www-data
        append: yes
      become_user: root
      become: yes
    
    - name: tell Lighttpd to use PHP
      command: lighty-enable-mod fastcgi-php userdir
      ignore_errors: True
      become_user: root
      become: yes

    - name: Stop Lighttpd
      service:
        name: lighttpd 
        state: stopped
      become_user: root
      become: yes

    - name: Start Lighttpd
      service:
        name: lighttpd
        state: started
        enabled: yes
      become_user: root
      become: yes

    - name: permissions on /media
      file:
        path: /media
        mode: 0777
        owner: pi
        group: pi
      become_user: root
      become: yes

    - name: Clean artifact path
      file:
        path: /var/www/html
        name: index.lighttpd.html
        state: absent   
      become_user: root
      become: yes

    - name: create index.html
      lineinfile:
        create: yes
        state: present
        dest: /var/www/html/index.html
        line: '<html><meta http-equiv="refresh" content="0; url=media/" /> </html>'
      become_user: root
      become: yes

    - name: link /media to the web interface 
      file:
        src: /media
        dest: /var/www/media
        state: link
        owner: pi
        group: pi
      become_user: root
      become: yes

    - name: Copy lighttpd.conf 
      copy:
        src: ./lighttpd.conf 
        dest: /etc/lighttpd/lighttpd.conf 
      become_user: root
      become: yes

    - name: unarchive DirectoryLister 
      unarchive:
        src: DirectoryLister.tar.gz
        dest: /media
      become_user: root
      become: yes

    - name: Copy files from config.php
      copy: 
        remote_src: true 
        src: /media/resources/default.config.php
        dest: /media/resources/config.php

    - name: Samba
      lineinfile:
        dest: /etc/samba/smb.conf
        regexp: '^[Media]'
        line: '[Media]\ncomment=My media\npath = /media\nbrowsable = yes\nguest ok = yes\nread only = yes\n'
      become_user: root
      become: yes

    - name: reload Samba
      service:
        name: smbd 
        state: started
      become_user: root
      become: yes

    - name: Config minidlna media_dir=/media
      lineinfile:
        dest: /etc/minidlna.conf
        regexp: '^media_dir='
        line: 'media_dir=/media'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna media_dir=/media/usb0/music
      lineinfile:
        dest: /etc/minidlna.conf
        insertafter: 'media_dir=.*$'
        line: 'media_dir=A,/media/usb0/music'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna media_dir=/media/usb0/video
      lineinfile:
        dest: /etc/minidlna.conf
        insertafter: 'media_dir=.*$'
        line: 'media_dir=V,/media/usb0/video'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna media_dir=/media/usb1/music
      lineinfile:
        dest: /etc/minidlna.conf
        insertafter: 'media_dir=.*$'
        line: 'media_dir=A,/media/usb1/music'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna media_dir=/media/usb1/video
      lineinfile:
        dest: /etc/minidlna.conf
        insertafter: 'media_dir=.*$'
        line: 'media_dir=V,/media/usb1/video'
        state: present
      become_user: root
      become: yes

    - name: Config minidlna friendly_name=Mediabox
      lineinfile:
        dest: /etc/minidlna.conf
        regexp: '^friendly_name='
        line: 'friendly_name=Mediabox'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna inotify=yes
      lineinfile:
        dest: /etc/minidlna.conf
        regexp: '^inotify='
        line: 'inotify=yes'
        state: present
      become_user: root
      become: yes
    - name: Config minidlna notify_interval=300
      lineinfile:
        dest: /etc/minidlna.conf
        regexp: '^notify_interval='
        line: 'notify_interval=300'
        state: present
      become_user: root
      become: yes

    - name: minidlna restart
      service:
        name: minidlna 
        state: restarted
      become_user: root
      become: yes
    - name: minidlna reload
      command: service minidlna force-reload
      become_user: root
      become: yes

    - name: Copy default_footer.php
      copy:
        src: ./default_footer.php
        dest: /media/resources/themes/bootstrap/default_footer.php

